### ISSUE TITLE
Speichern der berechneten Parameter optimieren

### ISSUE THREAD

**Issue by Fenox** [thomcz/aurora#14]
Bisher werden bei jedem Speichern/Laden Vorgang alle Daten gelesen bzw. gespeichert (Shared Preferences)
Ziel sollte eine Datenbank sein.
https://developer.android.com/guide/topics/data/data-storage.html#db

**Comment by thomcz** [comment]
da kommt eine exception, wenn ich daten lade, kann es sein, dass des speichern nicht funktioniert?

**android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0**
at android.database.AbstractCursor.checkPosition(AbstractCursor.java:432)
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
**at hrv.band.aurora.storage.SQLite.SQLController.loadData(SQLController.java:118)**
at hrv.band.aurora.view.adapter.StatisticValueAdapter.<init>(StatisticValueAdapter.java:44)
at hrv.band.aurora.view.fragment.StatisticFragment.onCreateView(StatisticFragment.java:41)
